export const FETCH_QUIZES_START='FETCH_QUIZES_START';
export const FETCH_QUIZES_SUCCESS='FETCH_QUIZES_SUCCESS';
export const FETCH_QUIZES_ERROR='FETCH_QUIZES_START';

export const FETCH_QUIZ_START='FETCH_QUIZ_START';
export const FETCH_QUIZ_SUCCESS='FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZ_ERROR='FETCH_QUIZ_SUCCESS';

export const SET_ANSWER_STATE = 'SET_ANSWER_STATE';
export const SET_QUIZ_FINISHED = 'SET_QUIZ_FINISHED';
export const SET_ACTIVE_QUESTION = 'SET_ACTIVE_QUESTION';
export const RESET_STATE = 'RESET_STATE';

export const CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION';
export const RESET_QUIZ_CREATOR = 'RESET_QUIZ_CREATOR';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTO_LOGOUT = 'AUTO_LOGOUT';